feat: [CDS-43019]: abort and cancel pipeline/workflow
harness/harness-go-sdk pull request #214
Opened 2022-11-03 19:29 UTC by rafaelmart1ns

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`

2022-11-04 12:56 UTC, lasdox commented on harness/cd/execution.go
> +func (c *ExecutionClient) AbortOrCancelWorkflowOrPipelineById(id, action, appId, envId string) (*executions.Response, error) {
please create an action enum, also i think we dont need anything more than execution id

2022-11-04 18:18 UTC, rafaelmart1ns commented on harness/cd/execution.go
> +func (c *ExecutionClient) AbortOrCancelWorkflowOrPipelineById(id, action, appId, envId string) (*executions.Response, error) {
done.

2022-11-21 15:00 UTC, micahlmartin requested changes
Code here looks good but there aren't any tests for it.

2022-11-21 20:44 UTC, micahlmartin approved these changes

2022-11-21 20:45 UTC, merged