[CDS-54856]: Adding OCI helm go files
harness/harness-go-sdk pull request #291
Opened 2023-03-09 11:23 UTC by namantalaycha10

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`

2023-03-10 13:52 UTC, rathodmeetsatish requested changes

2023-03-10 13:52 UTC, rathodmeetsatish commented on harness/cd/graphql/types.go
> +type OCIHelmRepoConnector struct {
cd folder is for cg we dont need this change

2023-03-10 13:52 UTC, rathodmeetsatish commented on harness/nextgen/enum_oci_helm_auth_types.go
> +
please refer harness/nextgen/enum_service_now_auth_types.go we need to add 1 block here

2023-03-13 06:18 UTC, namantalaycha10 commented on harness/cd/graphql/types.go
> +type OCIHelmRepoConnector struct {
Done

2023-03-13 06:18 UTC, namantalaycha10 commented on harness/nextgen/enum_oci_helm_auth_types.go
> +
Done

2023-03-13 13:22 UTC, rathodmeetsatish commented on harness/nextgen/model_oci_helm_username_password.go
> +	Username string `json:"username,omitempty"`
please do cmd+s on this file to fix indendation

2023-03-13 13:22 UTC, rathodmeetsatish requested changes

2023-03-13 13:22 UTC, rathodmeetsatish commented on harness/nextgen/model_oci_helm_connector.go
> +	ConnectorType string `json:"connectorType"`
please do cmd+s on this file to fix indendation

2023-03-13 13:31 UTC, rathodmeetsatish approved these changes

2023-03-13 13:37 UTC, abosii-harness approved these changes

2023-03-13 13:38 UTC, merged