chore: [CHAOS-6882]: Added Chaos resources including  client for registerInfraV2 API
harness/harness-go-sdk pull request #585
Opened 2024-10-14 12:06 UTC by Saranya-jena

## Describe your changes

## Comment Triggers

<details>
  <summary>PR Check triggers</summary>
  
- Build: `trigger build`
- gitleaks: `trigger gitleaks`

2024-10-15 07:55 UTC, rathodmeetsatish requested changes
Do we need these changes in go mod and go sum?

2024-10-15 08:08 UTC, Saranya-jena commented
> Do we need these changes in go mod and go sum?

@rathodmeetsatish I have removed the go mod changes, PTAL, thanks!

2024-10-15 08:10 UTC, rathodmeetsatish approved these changes

2024-10-15 08:50 UTC, SarthakJain26 approved these changes

2024-10-16 02:22 UTC, shovanmaity approved these changes
LGTM

2024-10-16 07:57 UTC, merged